version: "3.8"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
  graylog:
    image: swcc/docker-graylog2:latest
    ports: 
      - "9000:9000"
      - "12201:12201"
